In [1]:
import pandas as pd
import os
from icecream import ic

In [2]:
class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

In [3]:
with open("../../tlvmc-parkinsons-freezing-gait-prediction/tasks.csv") as file:
    dt = pd.read_csv(file)
    # create a new dataframe column by take the difference between begin and end columns
    dt['duration'] = dt['End'] - dt['Begin']
    # take the mean of the duration column
    mean = dt['duration'].mean()
    print(mean)
    # create a new dataframe by grouping each task according to their mean duration and also count 
    dt = dt.groupby('Task').agg({'duration': ['mean', 'count']})
    # sort dt by mean duration
    dt = dt.sort_values(by=[('duration', 'mean')], ascending=False)
    print(dt)

26.876835995740144
              duration      
                  mean count
Task                        
Rest1       178.256378    45
Turning-DT   72.360219   137
Rest2        60.590000    44
Hotspot2     57.677015   130
Hotspot2-C   57.270153    59
Turning-ST   56.416672   137
Turning-C    52.903918    61
MB7          30.991477    65
MB9          30.580231    65
TUG-DT       22.462824   267
MB8          21.458338    65
Hotspot1     19.805146   130
Hotspot1-C   19.661356    59
TUG-C        19.021294   119
4MW-C        18.444077    65
4MW          16.742168   137
TUG-ST       16.011014   278
MB3-L        13.335517   120
MB3-R        12.237815   124
MB10         12.152212    66
MB11         10.900179    67
MB13          8.758779    68
MB12          7.263586    70
MB2a          6.845810    42
MB2b          6.760318    66
MB1           5.218015    67
MB5           4.530712    66
MB6-R         4.162885    61
MB6-L         4.158355    62
MB6           4.023333     6
MB4           3.902638  

In [28]:
# open events.csv file read it and store it in a dataframe
with open("../../tlvmc-parkinsons-freezing-gait-prediction/events.csv") as file:
    df = pd.read_csv(file)
    # create a new dataframe column by take the difference between begin and end columns
    df['duration'] = df['Completion'] - df['Init']
    # take the mean of the duration column
    mean = df['duration'].mean()
    print(df)
    # create a new dataframe by grouping each task according to their mean duration and also count 
    df = df.groupby('Type').agg({'duration': ['sum', 'count']})
    # sort dt by mean duration
    df = df.sort_values(by=[('duration', 'sum')], ascending=False)
    # get numpy array of duration sum inversely scaled between 0 and 1
    counts = df[('duration', 'sum')].values
    print(counts)
    counts = 1 / counts # inverse scale
    counts = counts / counts.sum() * 3 # normalize
    print(counts, counts.sum())
    print(df)

              Id        Init  Completion     Type  Kinetic  duration
0     003f117e14     8.61312     14.7731     Turn      1.0   6.15998
1     009ee11563    11.38470     41.1847     Turn      1.0  29.80000
2     009ee11563    54.66470     58.7847     Turn      1.0   4.12000
3     011322847a    28.09660     30.2966     Turn      1.0   2.20000
4     01d0fe7266    30.31840     31.8784     Turn      1.0   1.56000
...          ...         ...         ...      ...      ...       ...
3707  f9fc61ce85   628.56000    631.6650  Walking      0.0   3.10500
3708  f9fc61ce85   782.49800    782.6530  Walking      1.0   0.15500
3709  f9fc61ce85   931.93900    933.4470     Turn      1.0   1.50800
3710  f9fc61ce85   990.85900    991.8580     Turn      0.0   0.99900
3711  f9fc61ce85  1180.46700   1181.2580     Turn      1.0   0.79100

[3712 rows x 6 columns]
[18949.98745  2609.41598  2390.72793]
[0.18531551 1.34579023 1.46889426] 3.0
                    duration      
                         sum count


In [21]:
with open("../../tlvmc-parkinsons-freezing-gait-prediction/daily_metadata.csv") as file:
    dt = pd.read_csv(file)
    print(dt)

            Id Subject  Visit Beginning of recording [00:00-23:59]
0   00c4c9313d  3d8b73      1                                10:19
1   07a96f89ec  a15b56      1                                07:30
2   0d1bc672a8  21e523      2                                08:30
3   0e333c9833  b068a2      1                                11:30
4   164adaed7b  ffa798      1                                13:00
..         ...     ...    ...                                  ...
60  e658b0aa3d  b7bd52      1                                08:00
61  ed0a487f20  268a2e      1                                12:30
62  ef1db3ca64  473568      1                                08:00
63  f16c5cda55  b6a627      1                                08:30
64  f3fa3bf72d  6ec6ba      1                                08:00

[65 rows x 4 columns]


In [22]:
with open("../../tlvmc-parkinsons-freezing-gait-prediction/subjects.csv") as file:
    dt = pd.read_csv(file)
    print(dt)

    Subject  Visit  Age Sex  YearsSinceDx  UPDRSIII_On  UPDRSIII_Off  NFOGQ
0    04fcdb    1.0   63   M           3.0         30.0           NaN      0
1    05595e    1.0   56   M           8.0         28.0           NaN      0
2    0967b2    1.0   59   M          10.0         38.0          48.0     19
3    0967b2    2.0   59   M          10.0         37.0          44.0     13
4    097078    NaN   70   F          10.0         27.0          50.0     20
..      ...    ...  ...  ..           ...          ...           ...    ...
168  f90887    1.0   72   M          16.0         35.0          46.0     26
169  fc1e1b    1.0   82   F          11.0         38.0          42.0     21
170  fe5d84    2.0   72   M          14.0         32.0          45.0     17
171  fe5d84    1.0   72   F          14.0         13.0          33.0     15
172  ffa798    1.0   55   F           9.0         14.0           NaN      0

[173 rows x 8 columns]


In [38]:
def get_data_amount(folder):
    files = os.listdir(folder)
    ic(
        folder, len(files)
    )

    #df_all = pd.DataFrame()
    total = 0
    for fname in files:
        if fname.endswith(".parquet"):
            df = pd.read_parquet(f"{folder}/{fname}")
        else:
            df = pd.read_csv(f"{folder}/{fname}")
        rows = len(df.index) 
        #ic(f"{fname} number of rows {rows}")
        total += rows
        #df_all = pd.concat([df_all, df])

    return total


In [34]:
ic(get_data_amount("../../tlvmc-parkinsons-freezing-gait-prediction/train/defog"))
ic(get_data_amount("../../tlvmc-parkinsons-freezing-gait-prediction/train/tdcsfog"))
ic(get_data_amount("../../tlvmc-parkinsons-freezing-gait-prediction/unlabeled"))

ic| f"Number of files in {folder}: {color.BLUE}{temp}{color.END}": ('Number of files in ../tlvmc-parkinsons-freezing-gait-prediction/train/defog: '
                                                                    '\x1b91\x1b')
ic| get_data_amount("../tlvmc-parkinsons-freezing-gait-prediction/train/defog"): 13525702
ic| f"Number of files in {folder}: {color.BLUE}{temp}{color.END}": ('Number of files in '
                                                                    '../tlvmc-parkinsons-freezing-gait-prediction/train/tdcsfog: '
                                                                    '\x1b833\x1b')
ic| get_data_amount("../tlvmc-parkinsons-freezing-gait-prediction/train/tdcsfog"): 7062672
ic| f"Number of files in {folder}: {color.BLUE}{temp}{color.END}": ('Number of files in ../tlvmc-parkinsons-freezing-gait-prediction/unlabeled: '
                                                                    '\x1b65\x1b')
ic| get_data_amount("../tlvmc-parkinsons-freezing-gait-pr

4220701887

In [10]:
import glob
import tqdm
import numpy as np
import pandas as pd
def event_analysis(folder_name):
    files = glob.glob(f"../../tlvmc-parkinsons-freezing-gait-prediction/train/{folder_name}/*.csv")
    print(files)
    events = []
    for f in files:
        df = pd.read_csv(f)
        # get the number of rows in the dataframe
        rows = len(df.index)
        # produce a list of sum of the columns 5, 6, 7
        event = df.iloc[:, 5:8].sum().values
        events.append((rows, sum(event)))
        total = np.array(events).sum(axis=0)
    return total
events = event_analysis("notype")
# reduce the list of tuples to a single tuple by summing the first and seconc columns

events


['../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/b77b68675d.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/8228c6fdee.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/296c84448e.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/2ea5e817f4.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/285c2210b3.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/71dd8ce20d.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/2054f1d5df.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/72853af746.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/3f02fa6e40.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/60dfb26b2c.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/816bd20e5d.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/train/notype/dd589529b5.csv', '../../tlvmc-parkinsons-freezing-gait-prediction/tr

array([10251114,  6832879])

In [39]:
ic(get_data_amount("../tlvmc-parkinsons-freezing-gait-prediction/train/notype"))

ic| folder: '../tlvmc-parkinsons-freezing-gait-prediction/train/notype'
    len(files): 46
ic| get_data_amount("../tlvmc-parkinsons-freezing-gait-prediction/train/notype"): 10251114


10251114